language: minimal
 
addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck

script: uname -a

after_success:
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.2
 
notifications:
 email:
   on_success: never
   on_failure: always